<?php
/**
 * Implements hook_block_info.
 */
function first_block_info() {
  $blocks['first'] = array('info' => t('First block'));
  return $blocks;
}

function first_block_view($delta = '') {
  global $user;
  $account = $user;
  $block['content'] = t('Hello @user from IP @host',array(
    '@user' => format_username($user), 
    '@host' => $account->hostname
  ));
  return $block;
}

// http://www.wdtutorials.com/drupal-7/drupal-7-how-to-create-module-part-1#.VV47xvlVhBc
// https://ezproxy.gl.iit.edu/login?url=http://dx.doi.org/10.1007/978-1-4302-2839-4